### ISSUE TITLE
reescribir el codigo EntradasTotales tag: 0103.py

### ISSUE THREAD

**Issue by Gabibelt** [CodeSystem2022/Alibaba_Proyecto_Tickets#18]
Al comienzo de la clase colocar una breve descripción de la funcionalidad de la clase y presentar el código comentado, Pasar el codigo de Java a Python con su respectivo tag: hacer commit a la rama **test** después hacen una PR y avisan al SM

**Comment by DenuArg** [comment]
Entendido!
