### ISSUE TITLE
Reescribir el código la clase EntradasVendidasNoVendidas tag: 0104.py

### ISSUE THREAD

**Issue by Gabibelt** [CodeSystem2022/Alibaba_Proyecto_Tickets#19]
Al comienzo de la clase colocar una breve descripción de la funcionalidad de la clase y presentar el código comentado, Pasar el codigo de Java a Python con su respectivo tag: hacer commit a la rama test después avisan al SM

**Comment by SebaLerotich** [comment]
Se verifico la creación de la clase.
