### ISSUE TITLE
Reescribir el código de LimpiarPantalla tag: 0106.py

### ISSUE THREAD

**Issue by Gabibelt** [CodeSystem2022/Alibaba_Proyecto_Tickets#21]
Al comienzo de la clase colocar una breve descripción de la funcionalidad de la clase y presentar el código comentado, Pasar el codigo de Java a Python con su respectivo tag: hacer commit a la rama test después avisan al SM

**Comment by SebaLerotich** [comment]
Se verifico que se creo la clase.
