### ISSUE TITLE
Reescribir el codigo de la clase Registro tag:0108.py

### ISSUE THREAD

**Issue by Gabibelt** [CodeSystem2022/Alibaba_Proyecto_Tickets#22]
Al comienzo de la clase colocar una breve descripción de la funcionalidad de la clase y presentar el código comentado, Pasar el codigo de Java a Python con su respectivo tag: hacer commit a la rama test después hacen una PR y avisan al SM

**Comment by SebaLerotich** [comment]
Se verifico la creacion de la clase.
